-- schema.sql
CREATE DATABASE IF NOT EXISTS fszn_db_product DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE fszn_db_product;

CREATE TABLE IF NOT EXISTS users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE [dbo].[users]
ADD [phone] NVARCHAR(20) NULL;
GO

ALTER TABLE [dbo].[users]
ADD [wechat] NVARCHAR(100) NULL;
GO
